In [ ]:
import pandas as pd

df = pd.read_excel('/content/Datathon Dataset (1).xlsx', dtype={'Offst.acct': str})
df.head()

,File Month,Name,Period,Account,Cost Ctr,Profit Ctr,WBS element,Ref.key (header) 1,Document Header Text,DocumentNo,...,Doc..Date,Amount in doc. curr.,Amt in loc.cur.,Curr.,LCurr,Category,Rate (USD),Amount in USD,Posting Period,Category Index
0,"Wednesday, 1 November, 2025",TW10,8,19500100,NaN,44000TW,NaN,NaN,86735700001,2000215182,...,2025-08-01,-425.0,-425.0,TWD,TWD,AP,30.6795,-13.85330,2025-08,1.0
1,"Wednesday, 1 November, 2025",TW10,8,19500100,NaN,44000TW,NaN,NaN,86735700003,2000215184,...,2025-08-01,-485.0,-485.0,TWD,TWD,AP,30.6795,-15.80906,2025-08,1.0
2,"Wednesday, 1 November, 2025",TW10,8,19500100,NaN,44000TW,NaN,NaN,86735700005,2000215186,...,2025-08-01,-460.0,-460.0,TWD,TWD,AP,30.6795,-14.99416,2025-08,1.0
3,"Wednesday, 1 November, 2025",TW10,8,19500100,NaN,44000TW,NaN,NaN,86735700006,2000215187,...,2025-08-01,-365.0,-365.0,TWD,TWD,AP,30.6795,-11.89754,2025-08,1.0
4,"Wednesday, 1 November, 2025",TW10,8,19500100,NaN,44000TW,NaN,NaN,86735700009,2000215190,...,2025-08-01,-465.0,-465.0,TWD,TWD,AP,30.6795,-15.15714,2025-08,1.0

In [ ]:
unique_vals = df['Offst.acct'].astype(str).str.strip().unique()
print(f"Total: {len(unique_vals)}")

targets = {'7177MY', '7327KR'}
found = targets.intersection(unique_vals)
missing = targets.difference(unique_vals)

print(f"Found: {found}")
print(f"Missing: {missing}")
print(unique_vals)

Total: 16
Found: {'7327KR', '7177MY'}
Missing: set()
['19500102' '19500109' '19500209' '19500409' '19500105' '19500103'
 '19500104' '81120100' '100111' '7327KR' '7177MY' '100126' '99999999'
 '81320100' '73400100' '19500203']

In [ ]:
clean_series = df['Offst.acct'].astype(str).str.strip()
mapping = df.groupby(clean_series)['Name of offsetting account'].unique()

for acct, names in mapping.items():
    print(f"Offst.acct: {acct}")
    print(*(f"  - {n}" for n in names), sep="\n")
    if len(names) > 1:
        print("  WARNING: Multiple names found!")
    print()

if (mapping.apply(len) == 1).all():
    print("All 'Offst.acct' values have unique names.")

Offst.acct: 100111
  - AstraZeneca UK Limited

Offst.acct: 100126
  - AstraZeneca AB

Offst.acct: 19500102
  - House Bank 1 - Clearing - EFT Payments

Offst.acct: 19500103
  - House Bank 1 - Clearing - EFT Receipts

Offst.acct: 19500104
  - House Bank 1 - Clearing - Cheques

Offst.acct: 19500105
  - House Bank 1 - Clearing - Cheques Issued

Offst.acct: 19500109
  - House Bank 1 - Clearing - Miscellaneous

Offst.acct: 19500203
  - House Bank 2 - Clearing - EFT Receipts

Offst.acct: 19500209
  - House Bank 2 - Clearing - Miscellaneous

Offst.acct: 19500409
  - House Bank 4 - Clearing - Miscellaneous

Offst.acct: 7177MY
  - ASTRAZENECA ASIA-PACIFIC BUSINESS

Offst.acct: 7327KR
  - AstraZeneca Korea Ltd

Offst.acct: 73400100
  - Bank Charges & Fees

Offst.acct: 81120100
  - External Interest Income - Bank Deposits

Offst.acct: 81320100
  - Ext Interest Expense - Short-Term Bank Borrowings

Offst.acct: 99999999
  - Conversion Dummy

All 'Offst.acct' values have unique names.

In [ ]:
df.drop(columns=['Name of offsetting account'], inplace=True, errors='ignore')
df.head()

,File Month,Name,Period,Account,Cost Ctr,Profit Ctr,WBS element,Ref.key (header) 1,Document Header Text,DocumentNo,...,Doc..Date,Amount in doc. curr.,Amt in loc.cur.,Curr.,LCurr,Category,Rate (USD),Amount in USD,Posting Period,Category Index
0,"Wednesday, 1 November, 2025",TW10,8,19500100,NaN,44000TW,NaN,NaN,86735700001,2000215182,...,2025-08-01,-425.0,-425.0,TWD,TWD,AP,30.6795,-13.85330,2025-08,1.0
1,"Wednesday, 1 November, 2025",TW10,8,19500100,NaN,44000TW,NaN,NaN,86735700003,2000215184,...,2025-08-01,-485.0,-485.0,TWD,TWD,AP,30.6795,-15.80906,2025-08,1.0
2,"Wednesday, 1 November, 2025",TW10,8,19500100,NaN,44000TW,NaN,NaN,86735700005,2000215186,...,2025-08-01,-460.0,-460.0,TWD,TWD,AP,30.6795,-14.99416,2025-08,1.0
3,"Wednesday, 1 November, 2025",TW10,8,19500100,NaN,44000TW,NaN,NaN,86735700006,2000215187,...,2025-08-01,-365.0,-365.0,TWD,TWD,AP,30.6795,-11.89754,2025-08,1.0
4,"Wednesday, 1 November, 2025",TW10,8,19500100,NaN,44000TW,NaN,NaN,86735700009,2000215190,...,2025-08-01,-465.0,-465.0,TWD,TWD,AP,30.6795,-15.15714,2025-08,1.0

In [ ]:
cols = ['File Month', 'Cost Ctr', 'WBS element', 'Ref.key (header) 1', 'Clrng doc.']
df.drop(columns=cols, inplace=True, errors='ignore')
df.head()

,Name,Period,Account,Profit Ctr,Document Header Text,DocumentNo,Type,PK,Offst.acct,Reference,...,Doc..Date,Amount in doc. curr.,Amt in loc.cur.,Curr.,LCurr,Category,Rate (USD),Amount in USD,Posting Period,Category Index
0,TW10,8,19500100,44000TW,86735700001,2000215182,ZB,50,19500102,HSBC1TWD0123142,...,2025-08-01,-425.0,-425.0,TWD,TWD,AP,30.6795,-13.85330,2025-08,1.0
1,TW10,8,19500100,44000TW,86735700003,2000215184,ZB,50,19500102,HSBC1TWD0123142,...,2025-08-01,-485.0,-485.0,TWD,TWD,AP,30.6795,-15.80906,2025-08,1.0
2,TW10,8,19500100,44000TW,86735700005,2000215186,ZB,50,19500102,HSBC1TWD0123142,...,2025-08-01,-460.0,-460.0,TWD,TWD,AP,30.6795,-14.99416,2025-08,1.0
3,TW10,8,19500100,44000TW,86735700006,2000215187,ZB,50,19500102,HSBC1TWD0123142,...,2025-08-01,-365.0,-365.0,TWD,TWD,AP,30.6795,-11.89754,2025-08,1.0
4,TW10,8,19500100,44000TW,86735700009,2000215190,ZB,50,19500102,HSBC1TWD0123142,...,2025-08-01,-465.0,-465.0,TWD,TWD,AP,30.6795,-15.15714,2025-08,1.0

In [ ]:
diffs = (df['Curr.'] != df['LCurr']).sum()
print(f"Identical: {diffs == 0}")

if diffs:
    print(f"Difference count: {diffs}")

Identical: False
Difference count: 6

In [ ]:
df.loc[df['Curr.'] != df['LCurr'], ['Curr.', 'LCurr']]

      Curr. LCurr
70437   GBP   IDR
70438   KRW   IDR
70439   USD   IDR
70442   GBP   IDR
70443   KRW   IDR
70444   USD   IDR

In [ ]:
print(f"IDR count: {(df['LCurr'] == 'IDR').sum()}")

IDR count: 15054

In [ ]:
df = df[df['Curr.'] == df['LCurr']]
print(f"Consistent: {(df['Curr.'] == df['LCurr']).all()}")

Consistent: True

In [ ]:
unique_vals = df['Offst.acct'].astype(str).str.strip().unique()
print(f"Total: {len(unique_vals)}")

targets = {'7177MY', '7327KR'}
found = targets.intersection(unique_vals)
missing = targets.difference(unique_vals)

print(f"Found: {found}")
print(f"Missing: {missing}")
print(unique_vals)

Total: 14
Found: set()
Missing: {'7327KR', '7177MY'}
['19500102' '19500109' '19500209' '19500409' '19500105' '19500103'
 '19500104' '81120100' '100111' '100126' '99999999' '81320100' '73400100'
 '19500203']

In [ ]:
print(f"IDR count: {(df['LCurr'] == 'IDR').sum()}")

IDR count: 15048

In [ ]:
df.drop(columns=['Document Header Text', 'DocumentNo'], inplace=True, errors='ignore')
df.head()

,Name,Period,Account,Profit Ctr,Type,PK,Offst.acct,Reference,Assignment,Pstng Date,Doc..Date,Amount in doc. curr.,Amt in loc.cur.,Curr.,LCurr,Category,Rate (USD),Amount in USD,Posting Period,Category Index
0,TW10,8,19500100,44000TW,ZB,50,19500102,HSBC1TWD0123142,200021,2025-08-01,2025-08-01,-425.0,-425.0,TWD,TWD,AP,30.6795,-13.85330,2025-08,1.0
1,TW10,8,19500100,44000TW,ZB,50,19500102,HSBC1TWD0123142,200021,2025-08-01,2025-08-01,-485.0,-485.0,TWD,TWD,AP,30.6795,-15.80906,2025-08,1.0
2,TW10,8,19500100,44000TW,ZB,50,19500102,HSBC1TWD0123142,200021,2025-08-01,2025-08-01,-460.0,-460.0,TWD,TWD,AP,30.6795,-14.99416,2025-08,1.0
3,TW10,8,19500100,44000TW,ZB,50,19500102,HSBC1TWD0123142,200021,2025-08-01,2025-08-01,-365.0,-365.0,TWD,TWD,AP,30.6795,-11.89754,2025-08,1.0
4,TW10,8,19500100,44000TW,ZB,50,19500102,HSBC1TWD0123142,200021,2025-08-01,2025-08-01,-465.0,-465.0,TWD,TWD,AP,30.6795,-15.15714,2025-08,1.0

In [ ]:
mask = df['Pstng Date'].dt.normalize() != df['Doc..Date'].dt.normalize()
print(f"Different dates count: {mask.sum()}")

if mask.any():
    display(df.loc[mask, ['Pstng Date', 'Doc..Date']].head())

Different dates count: 3

      Pstng Date  Doc..Date
70445 2025-06-28 2025-06-26
70446 2025-06-28 2025-06-26
70448 2025-06-28 2025-06-26

In [ ]:
df.drop(columns=['Doc..Date'], inplace=True, errors='ignore')
df.head()

,Name,Period,Account,Profit Ctr,Type,PK,Offst.acct,Reference,Assignment,Pstng Date,Amount in doc. curr.,Amt in loc.cur.,Curr.,LCurr,Category,Rate (USD),Amount in USD,Posting Period,Category Index
0,TW10,8,19500100,44000TW,ZB,50,19500102,HSBC1TWD0123142,200021,2025-08-01,-425.0,-425.0,TWD,TWD,AP,30.6795,-13.85330,2025-08,1.0
1,TW10,8,19500100,44000TW,ZB,50,19500102,HSBC1TWD0123142,200021,2025-08-01,-485.0,-485.0,TWD,TWD,AP,30.6795,-15.80906,2025-08,1.0
2,TW10,8,19500100,44000TW,ZB,50,19500102,HSBC1TWD0123142,200021,2025-08-01,-460.0,-460.0,TWD,TWD,AP,30.6795,-14.99416,2025-08,1.0
3,TW10,8,19500100,44000TW,ZB,50,19500102,HSBC1TWD0123142,200021,2025-08-01,-365.0,-365.0,TWD,TWD,AP,30.6795,-11.89754,2025-08,1.0
4,TW10,8,19500100,44000TW,ZB,50,19500102,HSBC1TWD0123142,200021,2025-08-01,-465.0,-465.0,TWD,TWD,AP,30.6795,-15.15714,2025-08,1.0

In [ ]:
cols = ['Amount in doc. curr.', 'Amt in loc.cur.']
df[cols] = df[cols].astype(float)

mask = df[cols[0]] != df[cols[1]]
print(f"Different amounts count: {mask.sum()}")

if mask.any():
    display(df.loc[mask, cols].head())

Different amounts count: 0

In [ ]:
df.drop(columns=['Amt in loc.cur.'], inplace=True, errors='ignore')
df.head()

,Name,Period,Account,Profit Ctr,Type,PK,Offst.acct,Reference,Assignment,Pstng Date,Amount in doc. curr.,Curr.,LCurr,Category,Rate (USD),Amount in USD,Posting Period,Category Index
0,TW10,8,19500100,44000TW,ZB,50,19500102,HSBC1TWD0123142,200021,2025-08-01,-425.0,TWD,TWD,AP,30.6795,-13.85330,2025-08,1.0
1,TW10,8,19500100,44000TW,ZB,50,19500102,HSBC1TWD0123142,200021,2025-08-01,-485.0,TWD,TWD,AP,30.6795,-15.80906,2025-08,1.0
2,TW10,8,19500100,44000TW,ZB,50,19500102,HSBC1TWD0123142,200021,2025-08-01,-460.0,TWD,TWD,AP,30.6795,-14.99416,2025-08,1.0
3,TW10,8,19500100,44000TW,ZB,50,19500102,HSBC1TWD0123142,200021,2025-08-01,-365.0,TWD,TWD,AP,30.6795,-11.89754,2025-08,1.0
4,TW10,8,19500100,44000TW,ZB,50,19500102,HSBC1TWD0123142,200021,2025-08-01,-465.0,TWD,TWD,AP,30.6795,-15.15714,2025-08,1.0

In [ ]:
print(f"Consistent: {(df['Curr.'] == df['LCurr']).all()}")
print(f"Curr unique: {df['Curr.'].unique()[:5]}")
print(f"LCurr unique: {df['LCurr'].unique()[:5]}")

Consistent: True
Curr unique: ['TWD' 'PHP' 'THB' 'IDR' 'MYR']
LCurr unique: ['TWD' 'PHP' 'THB' 'IDR' 'MYR']

In [ ]:
df.drop(columns=['LCurr'], inplace=True, errors='ignore')
df.head()

,Name,Period,Account,Profit Ctr,Type,PK,Offst.acct,Reference,Assignment,Pstng Date,Amount in doc. curr.,Curr.,Category,Rate (USD),Amount in USD,Posting Period,Category Index
0,TW10,8,19500100,44000TW,ZB,50,19500102,HSBC1TWD0123142,200021,2025-08-01,-425.0,TWD,AP,30.6795,-13.85330,2025-08,1.0
1,TW10,8,19500100,44000TW,ZB,50,19500102,HSBC1TWD0123142,200021,2025-08-01,-485.0,TWD,AP,30.6795,-15.80906,2025-08,1.0
2,TW10,8,19500100,44000TW,ZB,50,19500102,HSBC1TWD0123142,200021,2025-08-01,-460.0,TWD,AP,30.6795,-14.99416,2025-08,1.0
3,TW10,8,19500100,44000TW,ZB,50,19500102,HSBC1TWD0123142,200021,2025-08-01,-365.0,TWD,AP,30.6795,-11.89754,2025-08,1.0
4,TW10,8,19500100,44000TW,ZB,50,19500102,HSBC1TWD0123142,200021,2025-08-01,-465.0,TWD,AP,30.6795,-15.15714,2025-08,1.0

In [ ]:
df.drop(columns=['Amount in doc. curr.', 'Rate (USD)'], inplace=True, errors='ignore')
df.head()

,Name,Period,Account,Profit Ctr,Type,PK,Offst.acct,Reference,Assignment,Pstng Date,Curr.,Category,Amount in USD,Posting Period,Category Index
0,TW10,8,19500100,44000TW,ZB,50,19500102,HSBC1TWD0123142,200021,2025-08-01,TWD,AP,-13.85330,2025-08,1.0
1,TW10,8,19500100,44000TW,ZB,50,19500102,HSBC1TWD0123142,200021,2025-08-01,TWD,AP,-15.80906,2025-08,1.0
2,TW10,8,19500100,44000TW,ZB,50,19500102,HSBC1TWD0123142,200021,2025-08-01,TWD,AP,-14.99416,2025-08,1.0
3,TW10,8,19500100,44000TW,ZB,50,19500102,HSBC1TWD0123142,200021,2025-08-01,TWD,AP,-11.89754,2025-08,1.0
4,TW10,8,19500100,44000TW,ZB,50,19500102,HSBC1TWD0123142,200021,2025-08-01,TWD,AP,-15.15714,2025-08,1.0

In [ ]:
df['Period'] = pd.to_numeric(df['Period'], errors='coerce')
mask = df['Period'] != df['Pstng Date'].dt.month

print(f"Consistent: {~mask.any()}")

if mask.any():
    print(f"Mismatch count: {mask.sum()}")
    display(df.loc[mask, ['Period', 'Pstng Date']].assign(Derived_Month=df['Pstng Date'].dt.month).head())

Consistent: True

In [ ]:
columns_to_drop = ['Period']

existing_columns = df.columns.tolist()
columns_to_drop_actual = [col for col in columns_to_drop if col in existing_columns]

if columns_to_drop_actual:
    df = df.drop(columns=columns_to_drop_actual)
    print(f"Dropped columns: {columns_to_drop_actual}")
else:
    print("No specified columns found to drop.")

display(df.head())

Dropped columns: ['Period']

,Name,Account,Profit Ctr,Type,PK,Offst.acct,Reference,Assignment,Pstng Date,Curr.,Category,Amount in USD,Posting Period,Category Index
0,TW10,19500100,44000TW,ZB,50,19500102,HSBC1TWD0123142,200021,2025-08-01,TWD,AP,-13.85330,2025-08,1.0
1,TW10,19500100,44000TW,ZB,50,19500102,HSBC1TWD0123142,200021,2025-08-01,TWD,AP,-15.80906,2025-08,1.0
2,TW10,19500100,44000TW,ZB,50,19500102,HSBC1TWD0123142,200021,2025-08-01,TWD,AP,-14.99416,2025-08,1.0
3,TW10,19500100,44000TW,ZB,50,19500102,HSBC1TWD0123142,200021,2025-08-01,TWD,AP,-11.89754,2025-08,1.0
4,TW10,19500100,44000TW,ZB,50,19500102,HSBC1TWD0123142,200021,2025-08-01,TWD,AP,-15.15714,2025-08,1.0

In [ ]:
for name, currs in df.groupby('Name')['Curr.'].unique().items():
    print(f"Name: {name}\n  Currencies: {', '.join(currs)}\n")

Name: ID10
  Currencies: IDR

Name: KR10
  Currencies: KRW

Name: MY10
  Currencies: MYR

Name: PH10
  Currencies: PHP

Name: SS10
  Currencies: MYR

Name: TH10
  Currencies: THB

Name: TW10
  Currencies: TWD

Name: VN20
  Currencies: VND

In [ ]:
print("Unique 'Profit Ctr' types for each 'Name' value:\n" + "-"*47)

for name, ctrs in df.groupby('Name')['Profit Ctr'].unique().items():
    print(f"Name: {name}\n  Profit Centers: {', '.join(map(str, ctrs))}\n")

Unique 'Profit Ctr' types for each 'Name' value:
-----------------------------------------------
Name: ID10
  Profit Centers: 44000ID

Name: KR10
  Profit Centers: 44000KR

Name: MY10
  Profit Centers: 44000MY

Name: PH10
  Profit Centers: 44000PH

Name: SS10
  Profit Centers: 8620FIN

Name: TH10
  Profit Centers: 44000TH

Name: TW10
  Profit Centers: 44000TW

Name: VN20
  Profit Centers: 44000VN

In [ ]:
columns_to_drop = ['Profit Ctr']

existing_columns = df.columns.tolist()
columns_to_drop_actual = [col for col in columns_to_drop if col in existing_columns]

if columns_to_drop_actual:
    df = df.drop(columns=columns_to_drop_actual)
    print(f"Dropped columns: {columns_to_drop_actual}")
else:
    print("No specified columns found to drop.")

display(df.head())

Dropped columns: ['Profit Ctr']

,Name,Account,Type,PK,Offst.acct,Reference,Assignment,Pstng Date,Curr.,Category,Amount in USD,Posting Period,Category Index
0,TW10,19500100,ZB,50,19500102,HSBC1TWD0123142,200021,2025-08-01,TWD,AP,-13.85330,2025-08,1.0
1,TW10,19500100,ZB,50,19500102,HSBC1TWD0123142,200021,2025-08-01,TWD,AP,-15.80906,2025-08,1.0
2,TW10,19500100,ZB,50,19500102,HSBC1TWD0123142,200021,2025-08-01,TWD,AP,-14.99416,2025-08,1.0
3,TW10,19500100,ZB,50,19500102,HSBC1TWD0123142,200021,2025-08-01,TWD,AP,-11.89754,2025-08,1.0
4,TW10,19500100,ZB,50,19500102,HSBC1TWD0123142,200021,2025-08-01,TWD,AP,-15.15714,2025-08,1.0

In [ ]:
pstng_month = df['Pstng Date'].dt.month
period_month = df['Posting Period'].astype(str).str.split('-').str[1].astype(int)

mask = pstng_month != period_month
print(f"Consistent: {~mask.any()}")

if mask.any():
    print(f"Mismatch count: {mask.sum()}")
    display(df.loc[mask, ['Pstng Date', 'Posting Period']].head())

df.head()

Consistent: True

,Name,Account,Type,PK,Offst.acct,Reference,Assignment,Pstng Date,Curr.,Category,Amount in USD,Posting Period,Category Index
0,TW10,19500100,ZB,50,19500102,HSBC1TWD0123142,200021,2025-08-01,TWD,AP,-13.85330,2025-08,1.0
1,TW10,19500100,ZB,50,19500102,HSBC1TWD0123142,200021,2025-08-01,TWD,AP,-15.80906,2025-08,1.0
2,TW10,19500100,ZB,50,19500102,HSBC1TWD0123142,200021,2025-08-01,TWD,AP,-14.99416,2025-08,1.0
3,TW10,19500100,ZB,50,19500102,HSBC1TWD0123142,200021,2025-08-01,TWD,AP,-11.89754,2025-08,1.0
4,TW10,19500100,ZB,50,19500102,HSBC1TWD0123142,200021,2025-08-01,TWD,AP,-15.15714,2025-08,1.0

In [ ]:
for i, (name, ctrs) in enumerate(df.groupby('Category')['Category Index'].unique().items(), 1):
    print(i)
    print(f"Category: {name}\n  Category Index: {', '.join(map(str, ctrs))}\n")

1
Category: AP
  Category Index: 1.0

2
Category: AR
  Category Index: 25.0

3
Category: Bank charges
  Category Index: 11.0

4
Category: Custom and Duty
  Category Index: 8.0

5
Category: Dividend payout
  Category Index: 15.0

6
Category: Interest charges
  Category Index: 13.0

7
Category: Interest income
  Category Index: 23.0

8
Category: Loan payment
  Category Index: 12.0

9
Category: Loan payment and interest charges
  Category Index: 14.0

10
Category: Loan receipt
  Category Index: 19.0

11
Category: Netting AP
  Category Index: 2.0

12
Category: Netting AR
  Category Index: 16.0

13
Category: Non Netting AP
  Category Index: nan

14
Category: Non Netting AR
  Category Index: nan

15
Category: Other
  Category Index: nan

16
Category: Other receipt
  Category Index: 22.0

17
Category: Payroll
  Category Index: 9.0

18
Category: Statutory contribution
  Category Index: 10.0

19
Category: Tax payable
  Category Index: 7.0

In [ ]:
missing_rows = df[df['Category Index'].isna()]
print(f"Missing count: {len(missing_rows)}")
display(missing_rows)

Missing count: 59

,Name,Account,Type,PK,Offst.acct,Reference,Assignment,Pstng Date,Curr.,Category,Amount in USD,Posting Period,Category Index
68515,MY10,19500100,ZB,50,19500102,HSBC HSBC123243,90101500004,2025-10-26,MYR,Non Netting AP,-3095.38558,2025-10,NaN
68516,MY10,19500100,ZB,50,19500102,HSBC HSBC123118,84071300001,2025-05-26,MYR,Non Netting AP,-6950.29120,2025-05,NaN
70440,ID10,19500100,KZ,50,100111,NETTING CLEARING,Netting Clearing,2025-06-26,IDR,Other,-118589.74512,2025-06,NaN
70441,ID10,19500100,KZ,50,100126,NETTING CLEARING,Netting Clearing,2025-06-26,IDR,Other,-200756.42559,2025-06,NaN
70445,ID10,19500100,KZ,40,100111,NETTING CLEARING,Netting Clearing,2025-06-28,IDR,Other,131295.78924,2025-06,NaN
70446,ID10,19500100,KZ,40,100126,NETTING CLEARING,Netting Clearing,2025-06-28,IDR,Other,183407.10486,2025-06,NaN
70447,ID10,19500100,AB,40,99999999,NETTING RECEIPT,Netting Receipt,2025-06-26,IDR,Other,18293.93228,2025-06,NaN
70448,ID10,19500100,AB,50,99999999,NETTING RECEIPT,Netting Receipt,2025-06-28,IDR,Other,-15112.37884,2025-06,NaN
82013,MY10,19500100,ZB,50,19500102,HSBC HSBC123226,89298400007,2025-10-06,MYR,Non Netting AP,-8367.14119,2025-10,NaN
82015,MY10,19500100,ZB,50,19500102,HSBC HSBC123018,79066200001,2025-01-20,MYR,Non Netting AP,-9619.92553,2025-01,NaN
82017,MY10,19500100,ZB,50,19500102,HSBC HSBC123022,79340800003,2025-01-27,MYR,Non Netting AP,-6890.97216,2025-01,NaN
82018,MY10,19500100,ZB,50,19500102,HSBC HSBC123034,79892500018,2025-02-10,MYR,Non Netting AP,-2309.16270,2025-02,NaN
82020,MY10,19500100,ZB,50,19500102,HSBC HSBC123070,81547300003,2025-03-24,MYR,Non Netting AP,-5475.13344,2025-03,NaN
82023,MY10,19500100,ZB,50,19500102,HSBC HSBC123098,83110400008,2025-05-02,MYR,Non Netting AP,-26474.14626,2025-05,NaN
82024,MY10,19500100,ZB,50,19500102,HSBC HSBC123116,83990600001,2025-05-24,MYR,Non Netting AP,-2519.75934,2025-05,NaN
82025,MY10,19500100,ZB,50,19500102,HSBC HSBC123117,84029700002,2025-05-25,MYR,Non Netting AP,-2603.03035,2025-05,NaN
82026,MY10,19500100,ZB,50,19500102,HSBC HSBC123141,85192000004,2025-06-23,MYR,Non Netting AP,-3616.22972,2025-06,NaN
82029,MY10,19500100,ZB,50,19500102,HSBC HSBC123168,86533300001,2025-07-27,MYR,Non Netting AP,-465.28960,2025-07,NaN
82030,MY10,19500100,ZB,50,19500102,HSBC HSBC123185,87318900002,2025-08-16,MYR,Non Netting AP,-6986.75125,2025-08,NaN
82032,MY10,19500100,ZB,50,19500102,HSBC HSBC123193,87696600001,2025-08-25,MYR,Non Netting AP,-1962.60325,2025-08,NaN
82033,MY10,19500100,ZB,50,19500102,HSBC HSBC123193,87696600002,2025-08-25,MYR,Non Netting AP,-6460.72630,2025-08,NaN
82223,MY10,19500100,ZB,40,19500103,HSBC HSBC123092,82624700032,2025-04-20,MYR,Non Netting AR,484.53471,2025-04,NaN
82404,MY10,19500100,ZB,40,19500103,HSBC HSBC123240,89972800015,2025-10-23,MYR,Non Netting AR,5016.57132,2025-10,NaN
82405,MY10,19500100,ZB,40,19500103,HSBC HSBC123020,79261600036,2025-01-25,MYR,Non Netting AR,6286.25179,2025-01,NaN
82406,MY10,19500100,ZB,40,19500103,HSBC HSBC123021,79300600003,2025-01-26,MYR,Non Netting AR,12931.06661,2025-01,NaN
82407,MY10,19500100,ZB,40,19500103,HSBC HSBC123022,79340800019,2025-01-27,MYR,Non Netting AR,9406.52266,2025-01,NaN
82408,MY10,19500100,ZB,40,19500103,HSBC HSBC123074,81747500039,2025-03-29,MYR,Non Netting AR,8052.92580,2025-03,NaN
82409,MY10,19500100,ZB,40,19500103,HSBC HSBC123168,86533300002,2025-07-27,MYR,Non Netting AR,3334.42346,2025-07,NaN
82412,SS10,19500100,ZB,40,19500103,HSBC HSBC123015,78946500001,2025-01-17,MYR,Non Netting AR,5710.53885,2025-01,NaN
82413,SS10,19500100,ZB,40,19500103,HSBC HSBC123015,78946500002,2025-01-17,MYR,Non Netting AR,14231.46228,2025-01,NaN
82414,SS10,19500100,ZB,40,19500103,HSBC HSBC123016,78985000030,2025-01-18,MYR,Non Netting AR,6491.43726,2025-01,NaN
82415,SS10,19500100,ZB,40,19500103,HSBC HSBC123017,79027100002,2025-01-19,MYR,Non Netting AR,12973.58909,2025-01,NaN
82416,SS10,19500100,ZB,40,19500103,HSBC HSBC123018,79066800007,2025-01-20,MYR,Non Netting AR,6048.03276,2025-01,NaN
82419,SS10,19500100,ZB,40,19500103,HSBC HSBC123022,79341300005,2025-01-27,MYR,Non Netting AR,626.67513,2025-01,NaN
82420,SS10,19500100,ZB,40,19500103,HSBC HSBC123025,79494400002,2025-01-31,MYR,Non Netting AR,4124.02458,2025-01,NaN
82422,SS10,19500100,ZB,40,19500103,HSBC HSBC123060,81110000004,2025-03-13,MYR,Non Netting AR,10365.15348,2025-03,NaN
82423,SS10,19500100,ZB,40,19500103,HSBC HSBC123070,81547900006,2025-03-24,MYR,Non Netting AR,754.96239,2025-03,NaN
82424,SS10,19500100,ZB,40,19500103,HSBC HSBC123074,81748000050,2025-03-29,MYR,Non Netting AR,7688.21917,2025-03,NaN
82425,SS10,19500100,ZB,40,19500103,HSBC HSBC123109,83666300001,2025-05-16,MYR,Non Netting AR,13909.29508,2025-05,NaN
82426,SS10,19500100,ZB,40,19500103,HSBC HSBC123111,83748800001,2025-05-18,MYR,Non Netting AR,9466.65720,2025-05,NaN
82427,SS10,19500100,ZB,40,19500103,HSBC HSBC123112,83789400003,2025-05-19,MYR,Non Netting AR,101.76144,2025-05,NaN
82428,SS10,19500100,ZB,40,19500103,HSBC HSBC123114,83908600004,2025-05-22,MYR,Non Netting AR,486.55233,2025-05,NaN
82429,SS10,19500100,ZB,40,19500103,HSBC HSBC123116,83991100034,2025-05-24,MYR,Non Netting AR,3190.67889,2025-05,NaN
82430,SS10,19500100,ZB,40,19500103,HSBC HSBC123116,83991100035,2025-05-24,MYR,Non Netting AR,31.23790,2025-05,NaN
82431,SS10,19500100,ZB,40,19500103,HSBC HSBC123117,84030200002,2025-05-25,MYR,Non Netting AR,6516.85743,2025-05,NaN
82433,SS10,19500100,ZB,40,19500103,HSBC HSBC123118,84071800001,2025-05-26,MYR,Non Netting AR,33163.84976,2025-05,NaN
82434,SS10,19500100,ZB,40,19500103,HSBC HSBC123121,84228700002,2025-05-30,MYR,Non Netting AR,12500.65125,2025-05,NaN
82435,SS10,19500100,ZB,40,19500103,HSBC HSBC123121,84228700003,2025-05-30,MYR,Non Netting AR,9726.16750,2025-05,NaN
82436,SS10,19500100,ZB,40,19500103,HSBC HSBC123121,84228700004,2025-05-30,MYR,Non Netting AR,10854.73668,2025-05,NaN
82437,SS10,19500100,ZB,40,19500103,HSBC HSBC123123,84312800001,2025-06-01,MYR,Non Netting AR,8002.58245,2025-06,NaN
82438,SS10,19500100,ZB,40,19500103,HSBC HSBC123131,84747000006,2025-06-12,MYR,Non Netting AR,11.48383,2025-06,NaN
82439,SS10,19500100,ZB,40,19500103,HSBC HSBC123129,84788900007,2025-06-09,MYR,Non Netting AR,2875.05141,2025-06,NaN
82440,SS10,19500100,ZB,40,19500103,HSBC HSBC123133,84833100114,2025-06-14,MYR,Non Netting AR,1155.47533,2025-06,NaN
82441,SS10,19500100,ZB,40,19500103,HSBC HSBC123135,84916700002,2025-06-16,MYR,Non Netting AR,865.42911,2025-06,NaN
82442,SS10,19500100,ZB,40,19500103,HSBC HSBC123138,85074800001,2025-06-20,MYR,Non Netting AR,1895.25237,2025-06,NaN
82443,SS10,19500100,ZB,40,19500103,HSBC HSBC123138,85074800002,2025-06-20,MYR,Non Netting AR,26294.73840,2025-06,NaN
82444,SS10,19500100,ZB,40,19500103,HSBC HSBC123138,85074800003,2025-06-20,MYR,Non Netting AR,7508.91168,2025-06,NaN
82445,SS10,19500100,ZB,40,19500103,HSBC HSBC123138,85074800004,2025-06-20,MYR,Non Netting AR,9193.51426,2025-06,NaN
82446,SS10,19500100,ZB,40,19500103,HSBC HSBC123138,85074800005,2025-06-20,MYR,Non Netting AR,5995.91808,2025-06,NaN

In [ ]:
# 1. Define Static Mappings
category_declaration = {
    'Non Netting AP': 6,
    'Non Netting AR': 18,
}

# 2. Apply Static Map (preserves existing values if map returns NaN)
df['Category Index'] = df['Category'].map(category_declaration).fillna(df.get('Category Index', pd.Series([None]*len(df))))

# 3. Handle 'Other' Dynamic Logic (+ve -> 16, -ve -> 2)
mask_other = df['Category'] == 'Other'

# Apply overrides
df.loc[mask_other & (df['Amount in USD'] > 0), 'Category Index'] = 16
df.loc[mask_other & (df['Amount in USD'] < 0), 'Category Index'] = 2
# df.loc[mask_other & (df['Amount in USD'] == 0), 'Category Index'] = 22 # Optional fallback

# 4. Verify
print("Categories found:", df['Category'].dropna().unique())
print("Rows missing Category Index:", df['Category Index'].isna().sum())
display(df.head())

Categories found: ['AP' 'Payroll' 'Bank charges' 'Custom and Duty' 'Other receipt' 'AR'
 'Non Netting AP' 'Loan payment' 'Tax payable' 'Statutory contribution'
 'Interest income' 'Other' 'Interest charges'
 'Loan payment and interest charges' 'Loan receipt' 'Dividend payout'
 'Netting AP' 'Netting AR' 'Non Netting AR']
Rows missing Category Index: 0

,Name,Account,Type,PK,Offst.acct,Reference,Assignment,Pstng Date,Curr.,Category,Amount in USD,Posting Period,Category Index
0,TW10,19500100,ZB,50,19500102,HSBC1TWD0123142,200021,2025-08-01,TWD,AP,-13.85330,2025-08,1.0
1,TW10,19500100,ZB,50,19500102,HSBC1TWD0123142,200021,2025-08-01,TWD,AP,-15.80906,2025-08,1.0
2,TW10,19500100,ZB,50,19500102,HSBC1TWD0123142,200021,2025-08-01,TWD,AP,-14.99416,2025-08,1.0
3,TW10,19500100,ZB,50,19500102,HSBC1TWD0123142,200021,2025-08-01,TWD,AP,-11.89754,2025-08,1.0
4,TW10,19500100,ZB,50,19500102,HSBC1TWD0123142,200021,2025-08-01,TWD,AP,-15.15714,2025-08,1.0

In [ ]:
for i, (name, ctrs) in enumerate(df.groupby('Category')['Category Index'].unique().items(), 1):
    print(i)
    print(f"Category: {name}\n  Category Index: {', '.join(map(str, ctrs))}\n")

1
Category: AP
  Category Index: 1.0

2
Category: AR
  Category Index: 25.0

3
Category: Bank charges
  Category Index: 11.0

4
Category: Custom and Duty
  Category Index: 8.0

5
Category: Dividend payout
  Category Index: 15.0

6
Category: Interest charges
  Category Index: 13.0

7
Category: Interest income
  Category Index: 23.0

8
Category: Loan payment
  Category Index: 12.0

9
Category: Loan payment and interest charges
  Category Index: 14.0

10
Category: Loan receipt
  Category Index: 19.0

11
Category: Netting AP
  Category Index: 2.0

12
Category: Netting AR
  Category Index: 16.0

13
Category: Non Netting AP
  Category Index: 6.0

14
Category: Non Netting AR
  Category Index: 18.0

15
Category: Other
  Category Index: 2.0, 16.0

16
Category: Other receipt
  Category Index: 22.0

17
Category: Payroll
  Category Index: 9.0

18
Category: Statutory contribution
  Category Index: 10.0

19
Category: Tax payable
  Category Index: 7.0

In [ ]:
columns_to_drop = ['Category', 'Reference', 'Curr.','Type']

existing_columns = df.columns.tolist()
columns_to_drop_actual = [col for col in columns_to_drop if col in existing_columns]

if columns_to_drop_actual:
    df = df.drop(columns=columns_to_drop_actual)
    print(f"Dropped columns: {columns_to_drop_actual}")
else:
    print("No specified columns found to drop.")

display(df.head())

Dropped columns: ['Category', 'Reference', 'Curr.', 'Type']

,Name,Account,PK,Offst.acct,Assignment,Pstng Date,Amount in USD,Posting Period,Category Index
0,TW10,19500100,50,19500102,200021,2025-08-01,-13.85330,2025-08,1.0
1,TW10,19500100,50,19500102,200021,2025-08-01,-15.80906,2025-08,1.0
2,TW10,19500100,50,19500102,200021,2025-08-01,-14.99416,2025-08,1.0
3,TW10,19500100,50,19500102,200021,2025-08-01,-11.89754,2025-08,1.0
4,TW10,19500100,50,19500102,200021,2025-08-01,-15.15714,2025-08,1.0

In [ ]:
import json
import pandas as pd

calendar_json = """
{
  "2025-01": [
    ["2024-12-30", "2025-01-05"],
    ["2025-01-06", "2025-01-12"],
    ["2025-01-13", "2025-01-19"],
    ["2025-01-20", "2025-01-26"],
    ["2025-01-27", "2025-02-02"]
  ],
  "2025-02": [
    ["2025-01-27", "2025-02-02"],
    ["2025-02-03", "2025-02-09"],
    ["2025-02-10", "2025-02-16"],
    ["2025-02-17", "2025-02-23"],
    ["2025-02-24", "2025-03-02"]
  ],
  "2025-03": [
    ["2025-02-24", "2025-03-02"],
    ["2025-03-03", "2025-03-09"],
    ["2025-03-10", "2025-03-16"],
    ["2025-03-17", "2025-03-23"],
    ["2025-03-24", "2025-03-30"]
  ],
  "2025-04": [
    ["2025-03-31", "2025-04-06"],
    ["2025-04-07", "2025-04-13"],
    ["2025-04-14", "2025-04-20"],
    ["2025-04-21", "2025-04-27"],
    ["2025-04-28", "2025-05-04"]
  ],
  "2025-05": [
    ["2025-04-28", "2025-05-04"],
    ["2025-05-05", "2025-05-11"],
    ["2025-05-12", "2025-05-18"],
    ["2025-05-19", "2025-05-25"],
    ["2025-05-26", "2025-06-01"]
  ],
  "2025-06": [
    ["2025-05-26", "2025-06-01"],
    ["2025-06-02", "2025-06-08"],
    ["2025-06-09", "2025-06-15"],
    ["2025-06-16", "2025-06-22"],
    ["2025-06-23", "2025-06-29"]
  ],
  "2025-07": [
    ["2025-06-30", "2025-07-06"],
    ["2025-07-07", "2025-07-13"],
    ["2025-07-14", "2025-07-20"],
    ["2025-07-21", "2025-07-27"],
    ["2025-07-28", "2025-08-03"]
  ],
  "2025-08": [
    ["2025-07-28", "2025-08-03"],
    ["2025-08-04", "2025-08-10"],
    ["2025-08-11", "2025-08-17"],
    ["2025-08-18", "2025-08-24"],
    ["2025-08-25", "2025-08-31"]
  ],
  "2025-09": [
    ["2025-09-01", "2025-09-07"],
    ["2025-09-08", "2025-09-14"],
    ["2025-09-15", "2025-09-21"],
    ["2025-09-22", "2025-09-28"],
    ["2025-09-29", "2025-10-05"]
  ],
  "2025-10": [
    ["2025-09-29", "2025-10-05"],
    ["2025-10-06", "2025-10-12"],
    ["2025-10-13", "2025-10-19"],
    ["2025-10-20", "2025-10-26"],
    ["2025-10-27", "2025-11-02"]
  ],
  "2025-11": [
    ["2025-10-27", "2025-11-02"],
    ["2025-11-03", "2025-11-09"],
    ["2025-11-10", "2025-11-16"],
    ["2025-11-17", "2025-11-23"],
    ["2025-11-24", "2025-11-30"]
  ]
}
"""

calendar_data = json.loads(calendar_json)
week_rules = []
for period, weeks in calendar_data.items():
    for i, (start, end) in enumerate(weeks):
        week_rules.append({
            'start': pd.to_datetime(start),
            'end': pd.to_datetime(end),
            'weekly_period': f"{period}-W{i + 1}"
        })
rules_df = pd.DataFrame(week_rules)

df['Pstng Date'] = pd.to_datetime(df['Pstng Date'])

if 'Weekly_Period' not in df.columns:
    df['Weekly_Period'] = None

for _, rule in rules_df.iterrows():
    mask = (df['Pstng Date'] >= rule['start']) & (df['Pstng Date'] <= rule['end'])

    df.loc[mask, 'Weekly_Period'] = rule['weekly_period']

print(df.loc[df['Weekly_Period'].notna(), ['Pstng Date', 'Weekly_Period']].head())

  Pstng Date Weekly_Period
0 2025-08-01    2025-08-W1
1 2025-08-01    2025-08-W1
2 2025-08-01    2025-08-W1
3 2025-08-01    2025-08-W1
4 2025-08-01    2025-08-W1

In [ ]:
df['Category Index'] = pd.to_numeric(df['Category Index'], errors='coerce')

df.loc[(df['Category Index'] >= 1.0) & (df['Category Index'] <= 15.0), 'Flow_Code'] = 1

df.loc[(df['Category Index'] >= 16.0) & (df['Category Index'] <= 25.0), 'Flow_Code'] = 2

print(df['Flow_Code'].value_counts(dropna=False))

Flow_Code
1.0    81116
2.0     3406
Name: count, dtype: int64

In [ ]:
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
Index: 84522 entries, 0 to 84527
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Name            84522 non-null  object
 1   Account         84522 non-null  int64
 2   PK              84522 non-null  int64
 3   Offst.acct      84522 non-null  object
 4   Assignment      84522 non-null  object
 5   Pstng Date      84522 non-null  datetime64[ns]
 6   Amount in USD   84522 non-null  float64
 7   Posting Period  84522 non-null  object
 8   Category Index  84522 non-null  float64
 9   Weekly_Period   84522 non-null  object
 10  Flow_Code       84522 non-null  float64
dtypes: datetime64[ns](1), float64(3), int64(2), object(5)
memory usage: 9.8+ MB

,Name,Account,PK,Offst.acct,Assignment,Pstng Date,Amount in USD,Posting Period,Category Index,Weekly_Period,Flow_Code
0,TW10,19500100,50,19500102,200021,2025-08-01,-13.85330,2025-08,1.0,2025-08-W1,1.0
1,TW10,19500100,50,19500102,200021,2025-08-01,-15.80906,2025-08,1.0,2025-08-W1,1.0
2,TW10,19500100,50,19500102,200021,2025-08-01,-14.99416,2025-08,1.0,2025-08-W1,1.0
3,TW10,19500100,50,19500102,200021,2025-08-01,-11.89754,2025-08,1.0,2025-08-W1,1.0
4,TW10,19500100,50,19500102,200021,2025-08-01,-15.15714,2025-08,1.0,2025-08-W1,1.0

In [ ]:
df.to_excel('Datathoncleaned_data.xlsx', index=False)
print("Export complete: Datathoncleaned_data.xlsx")

Export complete: Datathoncleaned_data.xlsx